### ISSUE TITLE
re-cron is not available in yarn registry

### ISSUE THREAD

**Issue by joao-borges** [ua-cron/react#6]
I am trying to add `re-cron` to my app managed by yarn, no luck.

```
Arguments: 
  /Users/joaob/.nvm/versions/node/v14.18.2/bin/node /opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js add re-cron

PATH: 
  /Users/joaob/.nvm/versions/node/v14.18.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/java/bin:/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/opt/java/Contents/Home/bin:/opt/ffmpeg:/Library/Apple/usr/bin

Yarn version: 
  1.22.19

Node version: 
  14.18.2

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/re-cron: Not found
      at Request.params.callback [as _callback] (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:66145:18)
      at Request.self.callback (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:140890:22)
      at Request.emit (events.js:400:28)
      at Request.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:141862:10)
      at Request.emit (events.js:400:28)
      at IncomingMessage.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:141784:12)
      at Object.onceWrapper (events.js:519:28)
      at IncomingMessage.emit (events.js:412:35)
      at endReadableNT (internal/streams/readable.js:1334:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by BzenkoSergey** [comment]
@joao-borges try this command, it should work from version 2.0.4
```yarn add @sbzen/re-cron```
